[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
core_lib = { path = "../core_lib" }
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
